### ISSUE TITLE
Support multiple stations at once

### ISSUE THREAD

**Issue by bain-syrowik** [bsyrowik/BCTides#19]
Options:
1. Move Menu to long hold up on glance view, and use the Start button to cycle through stations
2. Use the Start button to cycle through stations, then get to Menu
3. Add a Menu option for which cached station data to display

**Comment by bsyrowik** [comment]
Within widget, menu can also be launched with long press on Up button.

**Comment by bsyrowik** [comment]
https://github.com/bsyrowik/BCTides/commit/7f7673fbbd9499308ad8d11cfba485345e7f021f

For page indicator

**Comment by bsyrowik** [comment]
Redo Get Data menu item:
```
Get Data
  All
  <Station 1>
  <Station 2>
  ...
```
